### ISSUE TITLE
WKWebView in SwiftUI causes Thread 1: EXC_BREAKPOINT crash

### ISSUE THREAD

**Issue by xernaj** [embrace-io/embrace-apple-sdk#10]
Hi,

I'm starting to evaluate the product and the ios sdk specifically and have run in to a problem where WKWebView in SwiftUI causes Thread 1: EXC_BREAKPOINT crash.

The debugger stops at "return originalImplementation(webView, Self.selector, htmlString, url)" within WKWebViewLoadHTMLStringSwizzler in WebViewCaptureService.swift.

I'll see if I can create a repro. For now the WKWebView is wrapped in swiftui and does not contain a URL as it's only for displaying HTML text (which is currently blank).

I've worked around the crash by setting captureServices to an empty array when setting up EmbraceOptions.

**Comment by ArielDemarco** [comment]
Thank you for reporting this issue! We have successfully reproduced the error and believe we have a fix for it. We'll work on implementing the fix shortly so you can test it out soon.

**Comment by ArielDemarco** [comment]
Hey @xernaj ! This should be now fixed on `main` with [this commit](https://github.com/embrace-io/embrace-apple-sdk/commit/995b06bd9053e1aff3ff0bd261d5a9544297e393). Please let us know if you run into any other issue while trying this out!
Again, thanks for the report and for helping us make Embrace better!
