### ISSUE TITLE
Unable to use with Apollo iOS SDK

### ISSUE THREAD

**Issue by mcmurrym** [embrace-io/embrace-apple-sdk#5]
I was hoping to use this library to export to an otel collector but it appears that when I start Embrace [Apollo's](https://github.com/apollographql/apollo-ios) URLSession delegate functions no longer are called, or at least some of them. Specifically
`func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data)`
`func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)`

**Comment by atreat** [comment]
@mcmurrym Can you provide some more information so we can dig into this? Would you mind providing a sample project that reproduces the issue? Specifically want to make sure of the Apollo version to you as well as the snippet of code to setup  the Apollo client.

Thanks for creating the issue and we'll take a look as soon as we can.

**Comment by mcmurrym** [comment]
Apollo 1.7.1

**Comment by mcmurrym** [comment]
https://github.com/mcmurrym/ApolloEmbrace-bug

Toggle `EmbraceController.start()` to see apollo complete or not complete

**Comment by atreat** [comment]
Thanks for the project, will dive in and take a look :+1:

**Comment by atreat** [comment]
Just wanted to provide an update that we have identified the issue and have been working on testing a potential fix.

**Comment by atreat** [comment]
Should be fixed with [af6639b16](https://github.com/embrace-io/embrace-apple-sdk/commit/af6639b1626cc7bb11c059c2d8c3d2527621c1a7). Let us know if you run into anything else!

Issue was caused by the handling of the underlying URLSessionTaskDelegate (`task.delegate` vs. `session.delegate`). Thanks again for the report!
